version: "3"

services:
  scheduler-db:
    container_name: "scheduler-db"
    image: "postgres:16"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: scheduler-db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - smart-payments

  scheduler-cache:
    container_name: "scheduler-cache"
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel debug --requirepass admin
    volumes:
      - scheduler-cache:/data
    ports:
      - "6381:6379"
    networks:
      - smart-payments

networks:
  smart-payments:
    external: true

volumes:
  scheduler-cache:
    driver: local
  auth-db: