version: "3"

services:
  auth-db:
    container_name: "auth-db"
    image: "postgres:16"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth-db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - smart-payments

  cache:
    container_name: "auth-cache"
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass admin
    volumes:
      - authenticator-cache:/data
    ports:
      - "6379:6379"
    networks:
      - smart-payments

networks:
  smart-payments:
    external: true

volumes:
  authenticator-cache:
    driver: local
  auth-db: