version: "3"

services:
  auth-db:
    container_name: "auth-db"
    image: "bitnami/postgresql:16"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth-db
    networks:
      - smart-payments

networks:
  smart-payments:
    external: true