version: "3"

services:
  messaging-gateway-db:
    container_name: "messaging-gateway-db"
    image: "postgres:16"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: messaging-gateway-db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - smart-payments

networks:
  smart-payments:
    external: true