version: "3"

services:
  subscription-db:
    container_name: "subscription-db"
    image: "postgres:16"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: subscription
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - smart-payments

  subscription-cache:
    container_name: "subscription-cache"
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel debug --requirepass admin
    volumes:
      - subscription-cache:/data
    ports:
      - "6380:6379"
    networks:
      - smart-payments

networks:
  smart-payments:
    external: true

volumes:
  subscription-cache:
    driver: local
  subscription-db: