spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/subscription
    username: pg
    password: 123

  kafka:
    enable: true
    bootstrap-servers: localhost:9092
    topics:
      new-user: user.new-user-register
      new-user-dlt: user.new-user-register.dlt
    consumer:
      auto-offset-reset: latest
      group-id: subscription_group

kong:
  url: http://localhost:8000

auth:
  jwt:
    secret: SUPER_SECRET_JWT

external:
  payment-gateway:
    uri: https://api-sandbox.asaas.com/v3/
    api-key: ${ASAAS_API_KEY}
  authenticator:
    uri: ${kong.url}/api/authenticator/
    external-services-key: INTERNAL_SUPER_SECRET