spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/subscription
    username: pg
    password: 123

  kafka:
    enable: true
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      group-id: subscription_group
    listener:
      auto-startup: true

  cache:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6380
      password: admin

kong:
  url: http://localhost:8000

auth:
  jwt:
    secret: SUPER_SECRET_JWT

external:
  payment-gateway:
    uri: https://api-sandbox.asaas.com/v3/
    api-key: ${ASAAS_API_KEY}
    webhook:
      api-key: SUPER_SECRET_KEY
  authenticator:
    uri: ${kong.url}/api/authenticator/
    external-services-key: INTERNAL_SUPER_SECRET