server:
  port: 0
  api-suffix: api/subscription

spring:
  application:
    name: subscription

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  flyway:
    placeholder-prefix: '#{'
    placeholder-suffix: '}'

kong:
  url: ${KONG_URL}

ui:
  url: ${UI_URL}

external:
  payment-gateway:
    uri: https://api.asaas.com/
    api-key: ${ASAAS_API_KEY}
