server:
  port: 8082
  api-suffix: api/subscription

spring:
  application:
    name: subscription

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  flyway:
    placeholder-prefix: '#{'
    placeholder-suffix: '}'

  kafka:
    enable: true
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    topics:
      new-user: user.new-user-register
      new-user-dlt: user.new-user-register.dlt
      new-purchase-charge: purchase-charge.new-charge
      new-purchase-charge-dlt: purchase-charge.new-charge.dlt
      confirmed-purchase-charge: purchase-charge.confirmed-charge
      confirmed-purchase-charge-dlt: purchase-charge.confirmed-charge.dlt
      overdue-purchase-charge: purchase-charge.overdue-charge
      overdue-purchase-charge-dlt: purchase-charge.overdue-charge
      mail-sender: mail.sender
      user-subscription-update: user.user-subscription-update
      user-subscription-update-dlt: user.user-subscription-update.dlt
      user-subscription-states: user.user-subscription-states.dlt
      user-subscription-states-dlt: user.user-subscription-states.dlt
    consumer:
      auto-offset-reset: latest
      group-id: subscription_group

  cache:
    type: redis
    enabled: true
    redis:
      cache-null-values: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

kong:
  url: ${KONG_URL}

auth:
  jwt:
    secret: ${JWT_SECRET}

external:
  payment-gateway:
    uri: https://api.asaas.com/
    api-key: ${ASAAS_API_KEY}
    webhook:
      api-key: ${ASAAS_WEBHOOK_API_KEY}
  authenticator:
    uri: ${AUTHENTICATOR_URI}
    external-services-key: ${EXTERNAL_SERVICES_KEY}
