server:
  port: 8081
  api-suffix: api/authenticator

spring:
  application:
    name: authenticator

  datasource:
    url: jdbc:postgresql://localhost:5431/auth-db
    username: pg
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  flyway:
    placeholder-prefix: '#{'
    placeholder-suffix: '}'

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      mail-sender: mail.sender
      mail-sender-dlt: mail.sender.dlt
    consumer:
      auto-offset-reset: latest
      group-id: authenticator_group

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

kong:
  url: http://localhost:8000

auth:
  jwt:
    secret: SUPER_SECRET_JWT
  services:
    internal:
      secret: INTERNAL_SUPER_SECRET
