server:
  port: 8081
  api-suffix: api/authenticator

spring:
  application:
    name: authenticator

  cache:
    type: redis
    redis:
      time-to-live: 60000

  data:
    redis:
      host: localhost
      port: 6379
      password: admin

  
  datasource:
    url: jdbc:postgresql://localhost:5431/auth-db
    username: pg
    password: 123

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  flyway:
    placeholder-prefix: '#{'
    placeholder-suffix: '}'

  kafka:
    enable: true
    bootstrap-servers: localhost:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

kong:
  url: http://localhost:8000

ui:
  url: http://localhost:3000

file:
  image:
    upload:
      bucket_name: "smart-payments-dev"

auth:
  jwt:
    secret: SUPER_SECRET_JWT
  services:
    internal:
      secret: INTERNAL_SUPER_SECRET

aws:
  s3:
    region: us-east-1