server:
  port: 8081
  api-suffix: api/authenticator

spring:
  application:
    name: authenticator
  datasource:
    url: jdbc:postgresql://localhost:5431/auth-db
    username: pg
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      mail-sender: mail.sender
      mail-sender-dlt: mail.sender.dlt
    consumer:
      auto-offset-reset: latest
      group-id: authenticator_group

kong:
  url: localhost:8000