spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/scheduler-db
    username: pg
    password: 123

kong:
  url: http://localhost:8000

ui:
  url: http://localhost:3000

auth:
  jwt:
    secret: SUPER_SECRET_JWT

external:
  authenticator:
    uri: ${kong.url}/api/authenticator/
    external-services-key: INTERNAL_SUPER_SECRET