spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/scheduler-db
    username: pg
    password: 123

  data:
    redis:
      host: localhost
      port: 6381
      password: admin

  kafka:
    enable: true
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:9094
    consumer:
      auto-offset-reset: latest
      group-id: subscription_group
    listener:
      auto-startup: true

kong:
  url: http://localhost:8000

ui:
  url: http://localhost:3000

auth:
  jwt:
    secret: SUPER_SECRET_JWT



external:
  authenticator:
    uri: ${kong.url}/api/authenticator/
    external-services-key: INTERNAL_SUPER_SECRET
  subscription:
    uri: ${kong.url}/api/subscription/
    external-services-key: INTERNAL_SUPER_SECRET